[package]
name = "saldowsd"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.5.21", features = ["derive", "cargo"] }
env_logger = "0.11.5"
log.workspace = true
saldo.workspace = true
