[package]
name = "saldowsd"
version.workspace = true
edition.workspace = true

[dependencies]
env_logger = "0.11.5"
log.workspace = true
miette = { workspace = true, features = ["fancy"] }
saldo.workspace = true
thiserror.workspace = true
