[package]
name = "process-corpus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
log.workspace = true

[dev-dependencies]
eyre.workspace = true
insta = { workspace = true, features = ["yaml"] }
rstest.workspace = true
