[package]
name = "saldo"
version.workspace = true
edition.workspace = true

[dependencies]
dashmap = "6.1.0"
flate2 = "1.0.35"
hashbrown = "0.15.2"
log = { workspace = true }
miette = "7.4.0"
quick-xml = { workspace = true }
thiserror = "2.0.4"
