[package]
name = "saldo"
version.workspace = true
edition.workspace = true

[dependencies]
flate2 = "1.0.35"
hashbrown.workspace = true
log = { workspace = true }
miette.workspace = true
quick-xml = { workspace = true }
thiserror.workspace = true
