[package]
name = "w2v"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
byteorder.workspace = true
hashbrown.workspace = true
miette.workspace = true
ndarray.workspace = true
thiserror.workspace = true
